/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LabelInfoPanel.java
 *
 * Created on 28-aug-2012, 18:33:04
 */
package tudelft.nas.graphgear.demointerface;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;

/**
 *
 * @author Ruud
 */
public class LabelInfoPanel extends javax.swing.JPanel {

    /** Creates new form LabelInfoPanel */
    public LabelInfoPanel() {
        initComponents();
        addResizeListener();
    }
    
    public LabelInfoPanel(String name, String text){
        initComponents();
        this.setSize(this.getPreferredSize());
        this.setVisible(true);
        this.setName(name);
        System.out.println("My size: " + this.getSize());
        Text.setText(text);
    }
    public void setAllignment(int a){
        Text.setHorizontalAlignment(a);
    }
    private void addResizeListener(){
        this.addComponentListener(new ComponentListener(){

            @Override
            public void componentResized(ComponentEvent e) {
                Dimension d = e.getComponent().getSize();
                Text.setBounds(2, 2, d.width-4, d.height-4);
            }

            @Override
            public void componentMoved(ComponentEvent e) {
                
            }

            @Override
            public void componentShown(ComponentEvent e) {
                
            }

            @Override
            public void componentHidden(ComponentEvent e) {
                
            }
            
        });
    }
    
    /**
     * Sets the colour of the panel
     * @param c colour of the panel
     */
    public void setColor(Color c){
        Text.setForeground(c);
    }
    
    /**
     * Sets the text of the label info panel
     * @param text text of the label info panel
     */
    public void setText(String text){
        Text.setText(text);
    }
            
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(0, 0));

        Text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Text.setText("InfoPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
