/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SliderControl.java
 *
 * Created on 22-aug-2012, 7:51:19
 */
package tudelft.nas.graphgear.demointerface;

/**
 *
 * @author Ruud
 */
public class SliderControl extends javax.swing.JPanel {

    /** Creates new form SliderControl */
    public SliderControl() {
        initComponents();
    }
    /**
     * Creates a new slider control.
     * @param caption Caption of the control
     * @param min minimum value of the slider
     * @param max maximum value of the slider
     */
    public SliderControl(String caption, int min, int max){
        initComponents();
        this.setVisible(true);
        this.setSize(this.getPreferredSize());
        Caption.setText(caption);
        Slider.setMinimum(min);
        Slider.setMaximum(max);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Slider = new javax.swing.JSlider();
        Caption = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(75, 50));
        setMinimumSize(new java.awt.Dimension(75, 50));
        setPreferredSize(new java.awt.Dimension(75, 50));

        Caption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Caption.setText("Node Size");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Caption, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(Slider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Caption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Caption;
    public javax.swing.JSlider Slider;
    // End of variables declaration//GEN-END:variables
}
